# Fly.io Application Configuration
# Wedding Guest Management API
# Created: October 18, 2025

app = "ngocquan-wedding-api"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[deploy]
  # Temporarily disabled: Migrations fail with P1001 on pooler
  # Run migrations manually if needed: flyctl ssh console -C "npx prisma migrate deploy"
  # release_command = "npx prisma migrate deploy"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[metrics]]
  port = 9091
  path = "/metrics"
