name: Test Secret (Debug)

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if secret exists
        env:
          DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL_POOLED }}
        run: |
          echo "Checking if DATABASE_URL secret is accessible..."
          
          if [ -z "$DATABASE_URL" ]; then
            echo "❌ ERROR: DATABASE_URL is EMPTY or NOT SET"
            echo "The secret 'SUPABASE_DATABASE_URL_POOLED' was not found or has no value"
            exit 1
          else
            echo "✅ SUCCESS: DATABASE_URL is set"
            echo "Connection string length: ${#DATABASE_URL} characters"
            
            # Show first 20 characters (safe, shows protocol)
            echo "Starts with: ${DATABASE_URL:0:20}..."
            
            # Show host (without password)
            echo "Host check: $(echo $DATABASE_URL | grep -o '@[^:]*' || echo 'Not found')"
            
            # Show port
            echo "Port check: $(echo $DATABASE_URL | grep -o ':[0-9]*/' | tr -d ':/' || echo 'Not found')"
          fi
